# Generated by Django 3.2 on 2021-12-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_microsyllabus_refrencedbooks_unitwisequestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrencedbooks',
            name='book_name',
            field=models.CharField(default='third edition', max_length=200),
            preserve_default=False,
        ),
    ]
