# Generated by Django 3.2 on 2021-12-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_news_technews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Tech_news', 'Tech_news')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
